#!/usr/bin/env python3
"""Codegen: emit the stdio MCP server from the canonical tool surface.

Reads ``mcp_server/tool_surface.py`` and writes ``mcp_server/server.py`` with
one typed FastMCP tool per family. Deterministic — running twice produces
byte-identical output. The hosted HTTP endpoint (``api/index.py``) consumes the
same spec at runtime, so the two surfaces stay in sync.
"""

from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from mcp_server import tool_surface as ts  # noqa: E402

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "mcp_server", "server.py")

_PY_TYPE = {
    "number": "float",
    "integer": "int",
    "array:number": "list[float]",
    "array:object": "list[dict]",
    "object": "dict",
}


def _field(name: str) -> str:
    return f"Field(description={name!r})"


def _annotation(name: str) -> str:
    spec = ts.PARAMS[name]
    py = _PY_TYPE[spec["type"]]
    return f"Annotated[Optional[{py}], {_field(spec['description'])}]"


def _emit_tool(tool: dict, lines: list[str]) -> None:
    name = tool["name"]
    if tool.get("compound"):
        params = [
            ("average_valuation", None),
            ("weights", None),
            ("scores", None),
            ("terminal_value", None),
            ("target_return", None),
            ("investment", None),
        ]
        sig = [f"{p}: {_annotation(p)}" for p, _ in params]
        call_names = [p for p, _ in params]
    else:
        enum = ", ".join(repr(m["key"]) for m in tool["methods"])
        method_desc = "Formula to apply. Options: " + "; ".join(f"{m['key']} = {m['summary']}" for m in tool["methods"])
        sig = [f"method: Annotated[Literal[{enum}], Field(description={method_desc!r})]"]
        names = ts._tool_param_names(tool)
        sig.extend(f"{n}: {_annotation(n)} = None" for n in names)
        call_names = ["method", *names]

    tags = ", ".join(repr(t) for t in tool["tags"])
    lines.append("")
    lines.append("@mcp.tool(")
    lines.append(f"    name={name!r},")
    lines.append(f"    title={tool['title']!r},")
    lines.append(f"    description={ts.describe(tool)!r},")
    lines.append("    output_schema=OUTPUT_SCHEMA,")
    lines.append("    annotations=COMMON_ANNOTATIONS,")
    lines.append(f"    tags={{{tags}}},")
    lines.append(")")
    lines.append(f"def {name}(")
    for entry in sig:
        lines.append(f"    {entry},")
    lines.append(") -> dict:")
    lines.append('    """' + tool["description"].split(". ")[0] + '."""')
    arg_pairs = ", ".join(f"{repr(n)}: {n}" for n in call_names)
    lines.append(f"    return call_tool({name!r}, {{{arg_pairs}}})")
    lines.append("")


HEADER = '''"""AUTO-GENERATED by scripts/generate_mcp.py — do not edit by hand.

Regenerate with: python scripts/generate_mcp.py
"""
# ruff: noqa: E501

from __future__ import annotations

import os
import sys
from typing import Annotated, Literal, Optional

from fastmcp import FastMCP
from pydantic import Field

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

try:  # run from the repo root (python mcp_server/server.py)
    from mcp_server.tool_surface import (
        COMMON_ANNOTATIONS,
        OUTPUT_SCHEMA,
        SERVER_NAME,
        SERVER_VERSION,
        call_tool,
    )
except ImportError:  # installed as a top-level module (pip install startup-valuation-mcp)
    from tool_surface import (  # type: ignore[no-redef]
        COMMON_ANNOTATIONS,
        OUTPUT_SCHEMA,
        SERVER_NAME,
        SERVER_VERSION,
        call_tool,
    )

mcp = FastMCP(SERVER_NAME, version=SERVER_VERSION)
'''

FOOTER = '''

def main() -> None:
    """Run the stdio MCP server (entry point)."""
    mcp.run()


if __name__ == "__main__":
    main()
'''


def main() -> None:
    lines: list[str] = [HEADER]
    for tool in ts.TOOLS:
        _emit_tool(tool, lines)
    lines.append(FOOTER)
    content = "\n".join(lines) + "\n"
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(content)
    print(f"wrote {OUT} ({ts.tool_count()} tools)")


if __name__ == "__main__":
    main()
