# mypy: ignore-errors
"""AUTO-GENERATED by scripts/generate_mcp.py — do not edit by hand.

Regenerate with: python scripts/generate_mcp.py

Excluded from type checking (and ruff via pyproject): the FastMCP decorators are
untyped when the optional ``fastmcp`` dependency is absent (as in CI's ``.[dev]``
install), so this generated file must not gate the type-check job.
"""
# ruff: noqa: E501

from __future__ import annotations

from typing import Annotated, Any, Literal, Optional

from fastmcp import FastMCP
from pydantic import Field

from startup_valuation.mcp import agent_guides
from startup_valuation.mcp.tool_surface import (
    COMMON_ANNOTATIONS,
    OUTPUT_SCHEMA,
    SERVER_NAME,
    SERVER_VERSION,
    call_tool,
)

mcp = FastMCP(SERVER_NAME, version=SERVER_VERSION)
agent_guides.register(mcp)


@mcp.tool(
    name='valuation_probability',
    title='Probability & Expected Value',
    description="Compute expected value and probability-weighted outcomes for startup scenarios: discrete E[X], joint probability of sequential events, probability-weighted value, VC portfolio expected return, Poisson event probability, and continuous E[X] over a range. Method selects the formula. Use for probability-weighted central estimates; for named bull/base/bear tables or option pricing use valuation_advanced, and to discount cash flows use valuation_time_value. Parameters apply per method: expected_value_discrete and probability_weighted need outcomes + probabilities; portfolio_return needs weights + returns; poisson needs mean_events + k; expected_value_continuous needs lower + upper. outcomes and probabilities must be equal length, and the probabilities should sum to 1. Routing: use valuation_advanced method 'scenario_analysis' for named bull/base/bear scenario tables, and its black_scholes/binomial methods for option pricing; use this tool for arbitrary outcome lists and probability-weighted central estimates. Only method is required; all other parameters are method-dependent, so supply those the selected method names and omit the rest (defaults apply where defined). Rate and decimal inputs are fractions (0.10 = 10%); probability and weight lists are in [0,1] and sum to 1. Returns value, method, inputs, assumptions, chapter, formula_number and calculation steps; pure arithmetic — no I/O and no external calls — rounded to 2 decimals, with no auth or rate limits. An unknown method, or a missing method-required parameter, returns an error instead of a value.",
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'probability', 'expected-value', 'risk'},
)
def valuation_probability(
    method: Annotated[Literal['expected_value_discrete', 'joint_probability', 'probability_weighted', 'portfolio_return', 'poisson', 'expected_value_continuous'], Field(description='Formula to apply. Options: expected_value_discrete = E[X] = Σ xᵢ·P(X=xᵢ) over a discrete outcome list.; joint_probability = P(total) = Π pᵢ for independent sequential events.; probability_weighted = E[V] = Σ pᵢ·Vᵢ.; portfolio_return = E[R] = Σ wᵢ·Rᵢ across a VC portfolio.; poisson = P(X=k) = e^-λ λ^k / k! for rare events.; expected_value_continuous = E[X] = ∫ x·f(x) dx over [lower, upper] on the standard normal.')],
    outcomes: Annotated[Optional[list[float]], Field(description='Possible outcome values x_i, in any currency unit (must match probabilities in length/order).')] = None,
    probabilities: Annotated[Optional[list[float]], Field(description='Probability of each outcome or stage, each in [0,1]; the list must sum to 1 where it is exhaustive.')] = None,
    weights: Annotated[Optional[list[float]], Field(description='Portfolio or factor weights, each in [0,1] and summing to 1 (same order as the paired value list).')] = None,
    returns: Annotated[Optional[list[float]], Field(description='Return of each asset or scenario as a decimal (0.20 = 20%), aligned with weights.')] = None,
    mean_events: Annotated[Optional[float], Field(description='Poisson mean λ = expected number of events in the interval.')] = None,
    k: Annotated[Optional[int], Field(description='Number of events k for the Poisson probability P(X=k); integer ≥ 0.')] = None,
    lower: Annotated[Optional[float], Field(description='Lower integration bound (standard-normal domain, e.g. -1.0).')] = None,
    upper: Annotated[Optional[float], Field(description='Upper integration bound (standard-normal domain, e.g. 1.0).')] = None,
) -> dict[str, Any]:
    """Compute expected value and probability-weighted outcomes for startup scenarios: discrete E[X], joint probability of sequential events, probability-weighted value, VC portfolio expected return, Poisson event probability, and continuous E[X] over a range."""
    return call_tool('valuation_probability', {'method': method, 'outcomes': outcomes, 'probabilities': probabilities, 'weights': weights, 'returns': returns, 'mean_events': mean_events, 'k': k, 'lower': lower, 'upper': upper})


@mcp.tool(
    name='valuation_time_value',
    title='Time Value of Money',
    description="Discount, compound, and forecast value over time: single future value PV, net present value of a cash-flow stream, annuity present value, discounted cash flow with a Gordon terminal value, constant-rate compound growth of revenue or cash flow, and the implied compound annual growth rate (CAGR). Method selects the formula. Use to convert future cash to today's value, to value a full forecast with a terminal value (dcf), to project a revenue or cash-flow series forward, or to derive the growth rate implied by two values; get the discount rate from valuation_capm or valuation_international. Parameters apply per method: present_value needs future_value + rate + periods; npv needs cash_flows + rate; annuity needs payment + rate + periods; dcf needs cash_flows + rate (optional: terminal_growth); compound_growth needs starting_value + growth_rate + periods; cagr needs starting_value + ending_value + periods. growth_rate must be greater than -1, cagr requires starting_value > 0 and periods > 0, and dcf requires rate greater than terminal_growth. Not for option values (use valuation_advanced) or for expected values over outcomes (use valuation_probability). Only method is required; all other parameters are method-dependent, so supply those the selected method names and omit the rest (defaults apply where defined). Rate and decimal inputs are fractions (0.10 = 10%); probability and weight lists are in [0,1] and sum to 1. Returns value, method, inputs, assumptions, chapter, formula_number and calculation steps; pure arithmetic — no I/O and no external calls — rounded to 2 decimals, with no auth or rate limits. An unknown method, or a missing method-required parameter, returns an error instead of a value.",
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'dcf', 'discounting', 'time-value', 'growth', 'forecasting'},
)
def valuation_time_value(
    method: Annotated[Literal['present_value', 'npv', 'annuity', 'compound_growth', 'cagr', 'dcf'], Field(description='Formula to apply. Options: present_value = PV = C / (1+r)^t.; npv = NPV = Σ Cₜ / (1+r)^t.; annuity = PV = P·[1-(1+r)^-n]/r.; compound_growth = V_n = V_0 (1+g)^n.; cagr = CAGR = (V_n / V_0)^(1/n) - 1.; dcf = DCF = Σ Cₜ/(1+r)^t + [C_n(1+g)/(r−g)]/(1+r)^n.')],
    future_value: Annotated[Optional[float], Field(description='Future cash amount to discount, in currency units.')] = None,
    rate: Annotated[Optional[float], Field(description='Per-period discount rate as a decimal (0.10 = 10%).')] = None,
    periods: Annotated[Optional[float], Field(description='Number of compounding periods, must be ≥ 1 (may be fractional).')] = None,
    cash_flows: Annotated[Optional[list[float]], Field(description='Cash flows by period, first element at t=1; negatives allowed for outflows.')] = None,
    payment: Annotated[Optional[float], Field(description='Recurring payment per period, in currency units.')] = None,
    starting_value: Annotated[Optional[float], Field(description='Value at t=0 (revenue or cash flow) to grow forward, in currency units.')] = None,
    growth_rate: Annotated[Optional[float], Field(description='Revenue growth rate as a decimal (0.40 = 40%).')] = None,
    ending_value: Annotated[Optional[float], Field(description='Value at t=n to compare against the starting value, in currency units.')] = None,
    terminal_growth: Annotated[Optional[float], Field(description='Perpetual growth rate g applied after the forecast window, as a decimal.')] = None,
) -> dict[str, Any]:
    """Discount, compound, and forecast value over time: single future value PV, net present value of a cash-flow stream, annuity present value, discounted cash flow with a Gordon terminal value, constant-rate compound growth of revenue or cash flow, and the implied compound annual growth rate (CAGR)."""
    return call_tool('valuation_time_value', {'method': method, 'future_value': future_value, 'rate': rate, 'periods': periods, 'cash_flows': cash_flows, 'payment': payment, 'starting_value': starting_value, 'growth_rate': growth_rate, 'ending_value': ending_value, 'terminal_growth': terminal_growth})


@mcp.tool(
    name='valuation_capm',
    title='CAPM & Cost of Equity',
    description='Estimate the cost of capital: standard CAPM, startup-adjusted CAPM with size and illiquidity premiums, portfolio beta from weighted asset betas, and WACC blending after-tax cost of equity and debt. Method selects the formula. Use to derive the discount rate that feeds valuation_time_value and DCF models; for cross-border rates add valuation_international. Parameters apply per method: capm needs risk_free_rate + beta + market_return; startup_capm adds size_premium and liquidity_premium; portfolio_beta needs weights + betas, which must be equal length; wacc needs equity_value + debt_value + cost_of_equity + cost_of_debt + tax_rate. Only method is required; all other parameters are method-dependent, so supply those the selected method names and omit the rest (defaults apply where defined). Rate and decimal inputs are fractions (0.10 = 10%); probability and weight lists are in [0,1] and sum to 1. Returns value, method, inputs, assumptions, chapter, formula_number and calculation steps; pure arithmetic — no I/O and no external calls — rounded to 2 decimals, with no auth or rate limits. An unknown method, or a missing method-required parameter, returns an error instead of a value.',
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'capm', 'cost-of-equity', 'beta', 'wacc', 'cost-of-capital'},
)
def valuation_capm(
    method: Annotated[Literal['capm', 'startup_capm', 'portfolio_beta', 'wacc'], Field(description='Formula to apply. Options: capm = E(R) = Rf + β·(E(Rm) - Rf).; startup_capm = r = Rf + β·MRP + size premium + illiquidity premium.; portfolio_beta = βp = Σ wᵢ·βᵢ.; wacc = WACC = (E/V)·Re + (D/V)·Rd·(1 − T).')],
    risk_free_rate: Annotated[Optional[float], Field(description='Risk-free rate as a decimal (e.g. 0.04 for 4%).')] = None,
    beta: Annotated[Optional[float], Field(description='Systematic risk beta (market = 1.0).')] = None,
    market_return: Annotated[Optional[float], Field(description='Expected market return as a decimal (e.g. 0.10 for 10%).')] = None,
    market_risk_premium: Annotated[Optional[float], Field(description='Market risk premium as a decimal (e.g. 0.06).')] = None,
    size_premium: Annotated[Optional[float], Field(description='Small-cap / size premium as a decimal.')] = None,
    liquidity_premium: Annotated[Optional[float], Field(description='Illiquidity premium as a decimal.')] = None,
    weights: Annotated[Optional[list[float]], Field(description='Portfolio or factor weights, each in [0,1] and summing to 1 (same order as the paired value list).')] = None,
    betas: Annotated[Optional[list[float]], Field(description='Asset betas aligned with weights; typically 0.5–3.0 (market = 1.0).')] = None,
    equity_value: Annotated[Optional[float], Field(description='Value of equity offered, currency units.')] = None,
    debt_value: Annotated[Optional[float], Field(description='Market value of debt, in currency units.')] = None,
    cost_of_equity: Annotated[Optional[float], Field(description='After-tax cost of equity Re as a decimal.')] = None,
    cost_of_debt: Annotated[Optional[float], Field(description='Pre-tax cost of debt Rd as a decimal.')] = None,
    tax_rate: Annotated[Optional[float], Field(description='Effective tax rate as a decimal in [0,1].')] = None,
) -> dict[str, Any]:
    """Estimate the cost of capital: standard CAPM, startup-adjusted CAPM with size and illiquidity premiums, portfolio beta from weighted asset betas, and WACC blending after-tax cost of equity and debt."""
    return call_tool('valuation_capm', {'method': method, 'risk_free_rate': risk_free_rate, 'beta': beta, 'market_return': market_return, 'market_risk_premium': market_risk_premium, 'size_premium': size_premium, 'liquidity_premium': liquidity_premium, 'weights': weights, 'betas': betas, 'equity_value': equity_value, 'debt_value': debt_value, 'cost_of_equity': cost_of_equity, 'cost_of_debt': cost_of_debt, 'tax_rate': tax_rate})


@mcp.tool(
    name='valuation_core',
    title='Pre-Revenue Core Methods',
    description="The textbook's pre-revenue methods: Scorecard, Berkus, Risk-Factor Summation, VC Method (post- and pre-money), and exit terminal value. Use these first for early-stage startups. Method selects the formula, and each method names its own parameters: scorecard needs average_valuation + weights + scores; berkus takes five factor awards; risk_factor needs base_valuation + risk_ratings; vc_post_money needs terminal_value + target_return; vc_pre_money needs post_money + investment; terminal_value needs projected_revenue + multiple; triangulated needs the scorecard inputs plus terminal_value/target_return/investment. Routing: for SAFEs, tokens, ESG, network effects, or data-moat methods use valuation_emerging; for options or bull/base/bear scenario tables use valuation_advanced; for public-comparable multiples use valuation_comparables. Only method is required; all other parameters are method-dependent, so supply those the selected method names and omit the rest (defaults apply where defined). Rate and decimal inputs are fractions (0.10 = 10%); probability and weight lists are in [0,1] and sum to 1. Returns value, method, inputs, assumptions, chapter, formula_number and calculation steps; pure arithmetic — no I/O and no external calls — rounded to 2 decimals, with no auth or rate limits. An unknown method, or a missing method-required parameter, returns an error instead of a value.",
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'pre-revenue', 'core', 'scorecard', 'berkus', 'vc-method'},
)
def valuation_core(
    method: Annotated[Literal['scorecard', 'berkus', 'risk_factor', 'vc_post_money', 'vc_pre_money', 'terminal_value', 'triangulated'], Field(description='Formula to apply. Options: scorecard = V = V_avg · Σ(wᵢ·sᵢ) across 7 factors.; berkus = V = Σ factor awards, each capped at $500K.; risk_factor = V = V_base + Σ(rᵢ·$250K) over 12 risks.; vc_post_money = Post = Terminal / target ROI.; vc_pre_money = Pre = Post - Investment.; terminal_value = Terminal = projected revenue × multiple.; triangulated = Runs Scorecard and the VC Method together and returns their mean.')],
    average_valuation: Annotated[Optional[float], Field(description='Average pre-revenue valuation for the sector, currency units.')] = None,
    weights: Annotated[Optional[list[float]], Field(description='Portfolio or factor weights, each in [0,1] and summing to 1 (same order as the paired value list).')] = None,
    scores: Annotated[Optional[list[float]], Field(description='Factor multipliers aligned with weights (1.0 = average, >1 above average).')] = None,
    sound_idea: Annotated[Optional[float], Field(description='Berkus award for soundness of the idea, 0 to 500,000 (USD).')] = None,
    prototype: Annotated[Optional[float], Field(description='Berkus award for prototype / technology, 0 to 500,000.')] = None,
    quality_team: Annotated[Optional[float], Field(description='Berkus award for management team, 0 to 500,000.')] = None,
    strategic_relationships: Annotated[Optional[float], Field(description='Berkus award for strategic relationships, 0 to 500,000.')] = None,
    product_rollout: Annotated[Optional[float], Field(description='Berkus award for product rollout / sales, 0 to 500,000.')] = None,
    base_valuation: Annotated[Optional[float], Field(description='Pre-adjustment baseline valuation, currency units.')] = None,
    risk_ratings: Annotated[Optional[list[float]], Field(description='12 risk factor ratings in [-2,2] (very low to very high); each unit shifts value ±250,000.')] = None,
    terminal_value: Annotated[Optional[float], Field(description='Expected exit / terminal value, currency units.')] = None,
    target_return: Annotated[Optional[float], Field(description='VC target return multiple (e.g. 10 for a 10x target).')] = None,
    post_money: Annotated[Optional[float], Field(description='Post-money valuation, currency units.')] = None,
    investment: Annotated[Optional[float], Field(description='Amount invested, currency units.')] = None,
    projected_revenue: Annotated[Optional[float], Field(description='Projected revenue at exit, currency units.')] = None,
    multiple: Annotated[Optional[float], Field(description='Exit or market multiple applied to the metric.')] = None,
) -> dict[str, Any]:
    """The textbook's pre-revenue methods: Scorecard, Berkus, Risk-Factor Summation, VC Method (post- and pre-money), and exit terminal value."""
    return call_tool('valuation_core', {'method': method, 'average_valuation': average_valuation, 'weights': weights, 'scores': scores, 'sound_idea': sound_idea, 'prototype': prototype, 'quality_team': quality_team, 'strategic_relationships': strategic_relationships, 'product_rollout': product_rollout, 'base_valuation': base_valuation, 'risk_ratings': risk_ratings, 'terminal_value': terminal_value, 'target_return': target_return, 'post_money': post_money, 'investment': investment, 'projected_revenue': projected_revenue, 'multiple': multiple})


@mcp.tool(
    name='valuation_advanced',
    title='Options & Scenario Analysis',
    description="Advanced techniques: Black-Scholes call value, binomial-tree option value, and scenario analysis. Method selects the technique. For a quick expected value over arbitrary outcome lists, prefer valuation_probability with method 'probability_weighted'; scenario_analysis here is for explicit named bull/base/bear scenario tables. Parameters apply per method: black_scholes and binomial need underlying + strike + risk_free_rate + volatility + time_to_maturity (binomial adds steps); scenario_analysis needs scenarios. Not for plain discounted cash flow — for that use valuation_time_value. Only method is required; all other parameters are method-dependent, so supply those the selected method names and omit the rest (defaults apply where defined). Rate and decimal inputs are fractions (0.10 = 10%); probability and weight lists are in [0,1] and sum to 1. Returns value, method, inputs, assumptions, chapter, formula_number and calculation steps; pure arithmetic — no I/O and no external calls — rounded to 2 decimals, with no auth or rate limits. An unknown method, or a missing method-required parameter, returns an error instead of a value.",
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'options', 'black-scholes', 'binomial', 'scenarios'},
)
def valuation_advanced(
    method: Annotated[Literal['black_scholes', 'binomial', 'scenario_analysis'], Field(description='Formula to apply. Options: black_scholes = C = N(d₁)S - N(d₂)Ke^(-rT).; binomial = Cox-Ross-Rubinstein binomial option value.; scenario_analysis = E[V] = Σ pᵢ·Vᵢ over named scenarios.')],
    underlying: Annotated[Optional[float], Field(description='Underlying asset value S, currency units.')] = None,
    strike: Annotated[Optional[float], Field(description='Strike / exercise price K, currency units.')] = None,
    risk_free_rate: Annotated[Optional[float], Field(description='Risk-free rate as a decimal (e.g. 0.04 for 4%).')] = None,
    volatility: Annotated[Optional[float], Field(description='Annualised volatility σ as a decimal (0.80 = 80%).')] = None,
    time_to_maturity: Annotated[Optional[float], Field(description='Time to expiry in years T, must be ≥ 0.')] = None,
    steps: Annotated[Optional[int], Field(description='Binomial tree time steps (integer ≥ 1; higher = more accurate).')] = None,
    scenarios: Annotated[Optional[list[dict[str, Any]]], Field(description='Scenario objects: {name: str, probability: 0-1, value: currency}; probabilities should sum to 1.')] = None,
) -> dict[str, Any]:
    """Advanced techniques: Black-Scholes call value, binomial-tree option value, and scenario analysis."""
    return call_tool('valuation_advanced', {'method': method, 'underlying': underlying, 'strike': strike, 'risk_free_rate': risk_free_rate, 'volatility': volatility, 'time_to_maturity': time_to_maturity, 'steps': steps, 'scenarios': scenarios})


@mcp.tool(
    name='valuation_comparables',
    title='Comparable Multiples',
    description='Market multiples from comparables: P/E, P/S, EV/EBITDA, EV/Revenue, and a regression-adjusted multiple. Method selects the ratio. Use when public comparables exist; for pre-revenue or private startups use valuation_core. Parameters apply per method: pe_ratio needs market_cap + net_income; ps_ratio needs market_cap + revenue; ev_ebitda needs enterprise_value + ebitda; ev_revenue needs enterprise_value + revenue; regression_multiple needs intercept + growth_rate + growth_coefficient (plus optional maturity/stage/geography terms). Only method is required; all other parameters are method-dependent, so supply those the selected method names and omit the rest (defaults apply where defined). Rate and decimal inputs are fractions (0.10 = 10%); probability and weight lists are in [0,1] and sum to 1. Returns value, method, inputs, assumptions, chapter, formula_number and calculation steps; pure arithmetic — no I/O and no external calls — rounded to 2 decimals, with no auth or rate limits. An unknown method, or a missing method-required parameter, returns an error instead of a value.',
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'multiples', 'comparables', 'market'},
)
def valuation_comparables(
    method: Annotated[Literal['pe_ratio', 'ps_ratio', 'ev_ebitda', 'ev_revenue', 'regression_multiple'], Field(description='Formula to apply. Options: pe_ratio = P/E = market cap / net income.; ps_ratio = P/S = market cap / revenue.; ev_ebitda = EV/EBITDA = enterprise value / EBITDA.; ev_revenue = EV/Revenue = enterprise value / revenue.; regression_multiple = Multiple = β0 + β1·g + β2·M + β3·S + β4·G.')],
    market_cap: Annotated[Optional[float], Field(description='Market capitalisation, currency units.')] = None,
    net_income: Annotated[Optional[float], Field(description='Net income (earnings), currency units.')] = None,
    revenue: Annotated[Optional[float], Field(description='Revenue for the period, currency units.')] = None,
    enterprise_value: Annotated[Optional[float], Field(description='Enterprise value (market cap + net debt), currency units.')] = None,
    ebitda: Annotated[Optional[float], Field(description='EBITDA, currency units.')] = None,
    intercept: Annotated[Optional[float], Field(description='Regression intercept β0 (base multiple).')] = None,
    growth_rate: Annotated[Optional[float], Field(description='Revenue growth rate as a decimal (0.40 = 40%).')] = None,
    growth_coefficient: Annotated[Optional[float], Field(description='Regression slope on growth (multiple points per unit growth).')] = None,
    market_maturity: Annotated[Optional[float], Field(description='Market maturity indicator.')] = None,
    maturity_coefficient: Annotated[Optional[float], Field(description='Regression slope on market maturity.')] = None,
    stage: Annotated[Optional[float], Field(description='Company stage indicator.')] = None,
    stage_coefficient: Annotated[Optional[float], Field(description='Regression slope on stage.')] = None,
    geography: Annotated[Optional[float], Field(description='Geography indicator.')] = None,
    geography_coefficient: Annotated[Optional[float], Field(description='Regression slope on geography.')] = None,
) -> dict[str, Any]:
    """Market multiples from comparables: P/E, P/S, EV/EBITDA, EV/Revenue, and a regression-adjusted multiple."""
    return call_tool('valuation_comparables', {'method': method, 'market_cap': market_cap, 'net_income': net_income, 'revenue': revenue, 'enterprise_value': enterprise_value, 'ebitda': ebitda, 'intercept': intercept, 'growth_rate': growth_rate, 'growth_coefficient': growth_coefficient, 'market_maturity': market_maturity, 'maturity_coefficient': maturity_coefficient, 'stage': stage, 'stage_coefficient': stage_coefficient, 'geography': geography, 'geography_coefficient': geography_coefficient})


@mcp.tool(
    name='valuation_saas',
    title='SaaS Metrics & Valuation',
    description='SaaS unit economics and valuation: LTV, CAC, MRR, ARR, net revenue retention, magic number, Rule of 40, CAC payback, and ARR revenue-multiple valuation. Method selects the metric. Use for subscription software; for marketplace GMV metrics use valuation_marketplace and for payments/lending use valuation_fintech. Parameters apply per method: ltv needs arpu + gross_margin + churn_rate; cac needs sales_marketing_expense + new_customers; arr needs subscription_values; nrr needs starting_revenue + ending_revenue; revenue_multiple needs arr + revenue_multiple. Not for company-level pre-revenue value — for that use valuation_core. Only method is required; all other parameters are method-dependent, so supply those the selected method names and omit the rest (defaults apply where defined). Rate and decimal inputs are fractions (0.10 = 10%); probability and weight lists are in [0,1] and sum to 1. Returns value, method, inputs, assumptions, chapter, formula_number and calculation steps; pure arithmetic — no I/O and no external calls — rounded to 2 decimals, with no auth or rate limits. An unknown method, or a missing method-required parameter, returns an error instead of a value.',
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'saas', 'arr', 'ltv', 'cac', 'retention'},
)
def valuation_saas(
    method: Annotated[Literal['ltv', 'cac', 'mrr', 'arr', 'nrr', 'magic_number', 'rule_of_40', 'cac_payback', 'revenue_multiple'], Field(description='Formula to apply. Options: ltv = LTV = ARPU × gross margin / churn.; cac = CAC = S&M expense / new customers.; mrr = MRR = ARR / 12 (reverse of ARR).; arr = ARR = Σ monthly subscriptions × 12.; nrr = NRR = (start + expansion) / start, net of churn.; magic_number = Magic Number = net new ARR / prior-quarter S&M.; rule_of_40 = Score = growth rate + profit margin.; cac_payback = Months to recover CAC from gross profit.; revenue_multiple = Valuation = ARR × multiple.')],
    arpu: Annotated[Optional[float], Field(description='Average revenue per user per month, currency units.')] = None,
    gross_margin: Annotated[Optional[float], Field(description='Gross margin as a decimal (0.80 = 80%).')] = None,
    churn_rate: Annotated[Optional[float], Field(description='Periodic churn rate as a decimal (0.02 = 2% per month).')] = None,
    sales_marketing_expense: Annotated[Optional[float], Field(description='Sales & marketing spend for the period, currency units.')] = None,
    new_customers: Annotated[Optional[int], Field(description='Number of customers acquired in the period.')] = None,
    arr_value: Annotated[Optional[float], Field(description='Annual recurring revenue, currency units.')] = None,
    subscription_values: Annotated[Optional[list[float]], Field(description='Monthly subscription revenue per customer (summed x12 for ARR).')] = None,
    starting_revenue: Annotated[Optional[float], Field(description='Revenue from the cohort at period start, currency units.')] = None,
    ending_revenue: Annotated[Optional[float], Field(description='Revenue from the same cohort at period end, currency units.')] = None,
    expansion_revenue: Annotated[Optional[float], Field(description='Expansion revenue from the cohort in the period.')] = None,
    net_new_arr: Annotated[Optional[float], Field(description='Net new ARR added in the period, currency units.')] = None,
    sm_expense_prior: Annotated[Optional[float], Field(description='Sales & marketing expense in the prior period, currency units.')] = None,
    growth_rate: Annotated[Optional[float], Field(description='Revenue growth rate as a decimal (0.40 = 40%).')] = None,
    profit_margin: Annotated[Optional[float], Field(description='Profit margin as a decimal (0.15 = 15%).')] = None,
    cac: Annotated[Optional[float], Field(description='Customer acquisition cost per customer, currency units.')] = None,
    mrr_per_customer: Annotated[Optional[float], Field(description='Monthly recurring revenue per customer, currency units.')] = None,
    arr: Annotated[Optional[float], Field(description='Annual recurring revenue, currency units.')] = None,
    revenue_multiple: Annotated[Optional[float], Field(description='SaaS revenue multiple (e.g. 8 for 8x ARR).')] = None,
) -> dict[str, Any]:
    """SaaS unit economics and valuation: LTV, CAC, MRR, ARR, net revenue retention, magic number, Rule of 40, CAC payback, and ARR revenue-multiple valuation."""
    return call_tool('valuation_saas', {'method': method, 'arpu': arpu, 'gross_margin': gross_margin, 'churn_rate': churn_rate, 'sales_marketing_expense': sales_marketing_expense, 'new_customers': new_customers, 'arr_value': arr_value, 'subscription_values': subscription_values, 'starting_revenue': starting_revenue, 'ending_revenue': ending_revenue, 'expansion_revenue': expansion_revenue, 'net_new_arr': net_new_arr, 'sm_expense_prior': sm_expense_prior, 'growth_rate': growth_rate, 'profit_margin': profit_margin, 'cac': cac, 'mrr_per_customer': mrr_per_customer, 'arr': arr, 'revenue_multiple': revenue_multiple})


@mcp.tool(
    name='valuation_marketplace',
    title='Marketplace Metrics',
    description='Marketplace health and valuation: take rate, GMV revenue-multiple valuation, buyer retention, and network density. Method selects the metric. Use for two-sided transaction marketplaces; for subscription software use valuation_saas. Parameters apply per method: take_rate needs revenue + gmv; gmv_multiple needs gmv + multiple; buyer_retention needs buyers_period_1 + buyers_repeat; network_density needs active_buyers + active_sellers + total_users. Only method is required; all other parameters are method-dependent, so supply those the selected method names and omit the rest (defaults apply where defined). Rate and decimal inputs are fractions (0.10 = 10%); probability and weight lists are in [0,1] and sum to 1. Returns value, method, inputs, assumptions, chapter, formula_number and calculation steps; pure arithmetic — no I/O and no external calls — rounded to 2 decimals, with no auth or rate limits. An unknown method, or a missing method-required parameter, returns an error instead of a value.',
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'marketplace', 'gmv', 'network-effects'},
)
def valuation_marketplace(
    method: Annotated[Literal['take_rate', 'gmv_multiple', 'buyer_retention', 'network_density'], Field(description='Formula to apply. Options: take_rate = Take rate = revenue / GMV.; gmv_multiple = Valuation = GMV × multiple.; buyer_retention = Retention = repeat buyers / base-period buyers.; network_density = Density = active buyers × active sellers / total users.')],
    revenue: Annotated[Optional[float], Field(description='Revenue for the period, currency units.')] = None,
    gmv: Annotated[Optional[float], Field(description='Gross merchandise value (total transaction volume), currency units.')] = None,
    multiple: Annotated[Optional[float], Field(description='Exit or market multiple applied to the metric.')] = None,
    buyers_period_1: Annotated[Optional[int], Field(description='Distinct buyers in the base period.')] = None,
    buyers_repeat: Annotated[Optional[int], Field(description='Distinct buyers from the base period who purchased again.')] = None,
    active_buyers: Annotated[Optional[int], Field(description='Active buyers in the period.')] = None,
    active_sellers: Annotated[Optional[int], Field(description='Active sellers in the period.')] = None,
    total_users: Annotated[Optional[int], Field(description='Total users (buyers + sellers) in the period.')] = None,
) -> dict[str, Any]:
    """Marketplace health and valuation: take rate, GMV revenue-multiple valuation, buyer retention, and network density."""
    return call_tool('valuation_marketplace', {'method': method, 'revenue': revenue, 'gmv': gmv, 'multiple': multiple, 'buyers_period_1': buyers_period_1, 'buyers_repeat': buyers_repeat, 'active_buyers': active_buyers, 'active_sellers': active_sellers, 'total_users': total_users})


@mcp.tool(
    name='valuation_fintech',
    title='Fintech Valuation',
    description='Value and size fintech business models: payment revenue, lending valuation, payment-processor DCF, and neobank customer-based valuation. Method selects the model. Use for payments, lending, and neobanks; for SaaS-style unit economics use valuation_saas. Parameters apply per method: payment_revenue needs transaction_volume + take_rate; lending needs loan_book + roe + pe_multiple; payment_processor adds growth_rate + discount_rate + terminal_multiple; neobank needs customers + arpu + gross_margin + churn_rate + pe_multiple. Only method is required; all other parameters are method-dependent, so supply those the selected method names and omit the rest (defaults apply where defined). Rate and decimal inputs are fractions (0.10 = 10%); probability and weight lists are in [0,1] and sum to 1. Returns value, method, inputs, assumptions, chapter, formula_number and calculation steps; pure arithmetic — no I/O and no external calls — rounded to 2 decimals, with no auth or rate limits. An unknown method, or a missing method-required parameter, returns an error instead of a value.',
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'fintech', 'payments', 'lending', 'neobank'},
)
def valuation_fintech(
    method: Annotated[Literal['payment_revenue', 'lending', 'payment_processor', 'neobank'], Field(description='Formula to apply. Options: payment_revenue = Revenue = volume × take rate.; lending = V = loan book × ROE × P/E - NPL reserves.; payment_processor = DCF of payment revenue with a terminal multiple.; neobank = Customer LTV × P/E applied to the customer base.')],
    transaction_volume: Annotated[Optional[float], Field(description='Total payment transaction volume, currency units.')] = None,
    take_rate: Annotated[Optional[float], Field(description='Take rate as a decimal (0.15 = 15% of GMV).')] = None,
    loan_book: Annotated[Optional[float], Field(description='Outstanding loan book / principal, currency units.')] = None,
    roe: Annotated[Optional[float], Field(description='Return on equity as a decimal (0.20 = 20%).')] = None,
    pe_multiple: Annotated[Optional[float], Field(description='Price/earnings multiple applied to earnings.')] = None,
    npl_reserves: Annotated[Optional[float], Field(description='Non-performing loan reserves deducted, currency units.')] = None,
    growth_rate: Annotated[Optional[float], Field(description='Revenue growth rate as a decimal (0.40 = 40%).')] = None,
    discount_rate: Annotated[Optional[float], Field(description='Discount rate as a decimal (0.12 = 12%).')] = None,
    terminal_multiple: Annotated[Optional[float], Field(description='Terminal value multiple applied at the horizon.')] = None,
    years: Annotated[Optional[int], Field(description='Forecast horizon in years; integer ≥ 1.')] = None,
    customers: Annotated[Optional[int], Field(description='Number of customers.')] = None,
    arpu: Annotated[Optional[float], Field(description='Average revenue per user per month, currency units.')] = None,
    gross_margin: Annotated[Optional[float], Field(description='Gross margin as a decimal (0.80 = 80%).')] = None,
    churn_rate: Annotated[Optional[float], Field(description='Periodic churn rate as a decimal (0.02 = 2% per month).')] = None,
) -> dict[str, Any]:
    """Value and size fintech business models: payment revenue, lending valuation, payment-processor DCF, and neobank customer-based valuation."""
    return call_tool('valuation_fintech', {'method': method, 'transaction_volume': transaction_volume, 'take_rate': take_rate, 'loan_book': loan_book, 'roe': roe, 'pe_multiple': pe_multiple, 'npl_reserves': npl_reserves, 'growth_rate': growth_rate, 'discount_rate': discount_rate, 'terminal_multiple': terminal_multiple, 'years': years, 'customers': customers, 'arpu': arpu, 'gross_margin': gross_margin, 'churn_rate': churn_rate})


@mcp.tool(
    name='valuation_biotech',
    title='Biotech Pipeline Valuation',
    description='Risk-adjusted biotech valuation: peak sales, decision-tree expected value, and full pipeline rNPV across drugs. Method selects the model. Use for pharma/drug pipelines; for hardware or deep tech use valuation_hardware. Parameters apply per method: peak_sales needs patient_population + penetration + price; decision_tree needs probabilities + terminal_value; pipeline needs drugs + discount_rate. Not for hardware or deep tech — for that use valuation_hardware. Only method is required; all other parameters are method-dependent, so supply those the selected method names and omit the rest (defaults apply where defined). Rate and decimal inputs are fractions (0.10 = 10%); probability and weight lists are in [0,1] and sum to 1. Returns value, method, inputs, assumptions, chapter, formula_number and calculation steps; pure arithmetic — no I/O and no external calls — rounded to 2 decimals, with no auth or rate limits. An unknown method, or a missing method-required parameter, returns an error instead of a value.',
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'biotech', 'pharma', 'pipeline', 'rnpv'},
)
def valuation_biotech(
    method: Annotated[Literal['peak_sales', 'decision_tree', 'pipeline'], Field(description='Formula to apply. Options: peak_sales = Peak = population × penetration × price × compliance.; decision_tree = EV = Π pᵢ × terminal value.; pipeline = V = Σ(peak sales × multiple × P_success) / (1+r)^n.')],
    patient_population: Annotated[Optional[float], Field(description='Target patient population treated per year.')] = None,
    penetration: Annotated[Optional[float], Field(description='Market penetration as a decimal (0.10 = 10%).')] = None,
    price: Annotated[Optional[float], Field(description='Price per unit / treatment, currency units.')] = None,
    compliance: Annotated[Optional[float], Field(description='Compliance / adherence rate as a decimal.')] = None,
    probabilities: Annotated[Optional[list[float]], Field(description='Probability of each outcome or stage, each in [0,1]; the list must sum to 1 where it is exhaustive.')] = None,
    terminal_value: Annotated[Optional[float], Field(description='Expected exit / terminal value, currency units.')] = None,
    drugs: Annotated[Optional[list[dict[str, Any]]], Field(description='Pipeline drugs: {name, peak_sales, probability, years_to_market, multiple(optional)}.')] = None,
    discount_rate: Annotated[Optional[float], Field(description='Discount rate as a decimal (0.12 = 12%).')] = None,
) -> dict[str, Any]:
    """Risk-adjusted biotech valuation: peak sales, decision-tree expected value, and full pipeline rNPV across drugs."""
    return call_tool('valuation_biotech', {'method': method, 'patient_population': patient_population, 'penetration': penetration, 'price': price, 'compliance': compliance, 'probabilities': probabilities, 'terminal_value': terminal_value, 'drugs': drugs, 'discount_rate': discount_rate})


@mcp.tool(
    name='valuation_hardware',
    title='Hardware & Unit Economics',
    description='Hardware and deep-tech valuation: TRL-risk-adjusted valuation, gross margin, and break-even volume. Method selects the metric. Use for hardware and deep tech with technology-readiness risk; for drug pipelines use valuation_biotech. Parameters apply per method: trl needs market_size + market_share + margin + multiple + trl_discount; gross_margin needs asp + variable_cost; break_even_volume needs fixed_costs + asp + variable_cost. Not for drug pipelines — for those use valuation_biotech. Only method is required; all other parameters are method-dependent, so supply those the selected method names and omit the rest (defaults apply where defined). Rate and decimal inputs are fractions (0.10 = 10%); probability and weight lists are in [0,1] and sum to 1. Returns value, method, inputs, assumptions, chapter, formula_number and calculation steps; pure arithmetic — no I/O and no external calls — rounded to 2 decimals, with no auth or rate limits. An unknown method, or a missing method-required parameter, returns an error instead of a value.',
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'hardware', 'trl', 'unit-economics'},
)
def valuation_hardware(
    method: Annotated[Literal['trl', 'gross_margin', 'break_even_volume'], Field(description='Formula to apply. Options: trl = V = market × share × margin × multiple × (1 - TRL discount).; gross_margin = GM = (ASP - COGS) / ASP.; break_even_volume = Units = fixed costs / (ASP - variable cost).')],
    market_size: Annotated[Optional[float], Field(description='Total addressable market, currency units.')] = None,
    market_share: Annotated[Optional[float], Field(description='Target market share as a decimal in [0,1].')] = None,
    margin: Annotated[Optional[float], Field(description='Profit margin as a decimal.')] = None,
    multiple: Annotated[Optional[float], Field(description='Exit or market multiple applied to the metric.')] = None,
    trl_discount: Annotated[Optional[float], Field(description='TRL risk discount as a decimal (applied as 1 - discount).')] = None,
    asp: Annotated[Optional[float], Field(description='Average selling price per unit, currency units.')] = None,
    variable_cost: Annotated[Optional[float], Field(description='Variable cost per unit, currency units.')] = None,
    fixed_costs: Annotated[Optional[float], Field(description='Fixed costs for the period, currency units.')] = None,
) -> dict[str, Any]:
    """Hardware and deep-tech valuation: TRL-risk-adjusted valuation, gross margin, and break-even volume."""
    return call_tool('valuation_hardware', {'method': method, 'market_size': market_size, 'market_share': market_share, 'margin': margin, 'multiple': multiple, 'trl_discount': trl_discount, 'asp': asp, 'variable_cost': variable_cost, 'fixed_costs': fixed_costs})


@mcp.tool(
    name='valuation_international',
    title='International Valuation',
    description='Cross-border adjustments: purchasing-power parity, country risk premium, and international CAPM. Method selects the adjustment. Use for cross-border cash flows and country risk; pair with valuation_capm and valuation_time_value. Parameters apply per method: ppp needs spot_rate + inflation_foreign + inflation_domestic; country_risk_premium needs sovereign_yield + us_treasury_yield; intl_capm needs risk_free_rate + beta + mrp + crp. Not for the domestic cost of equity — for that use valuation_capm. Only method is required; all other parameters are method-dependent, so supply those the selected method names and omit the rest (defaults apply where defined). Rate and decimal inputs are fractions (0.10 = 10%); probability and weight lists are in [0,1] and sum to 1. Returns value, method, inputs, assumptions, chapter, formula_number and calculation steps; pure arithmetic — no I/O and no external calls — rounded to 2 decimals, with no auth or rate limits. An unknown method, or a missing method-required parameter, returns an error instead of a value.',
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'international', 'fx', 'country-risk'},
)
def valuation_international(
    method: Annotated[Literal['ppp', 'country_risk_premium', 'intl_capm'], Field(description='Formula to apply. Options: ppp = Eₜ = E₀·(1+π_foreign)/(1+π_domestic).; country_risk_premium = CRP = sovereign yield - US Treasury yield.; intl_capm = r = Rf + β·MRP + CRP.')],
    spot_rate: Annotated[Optional[float], Field(description='Spot FX rate (domestic per foreign), e.g. 7.2 CNY/USD.')] = None,
    inflation_foreign: Annotated[Optional[float], Field(description='Foreign inflation rate as a decimal.')] = None,
    inflation_domestic: Annotated[Optional[float], Field(description='Domestic inflation rate as a decimal.')] = None,
    sovereign_yield: Annotated[Optional[float], Field(description='Foreign sovereign bond yield as a decimal.')] = None,
    us_treasury_yield: Annotated[Optional[float], Field(description='US Treasury yield as a decimal.')] = None,
    risk_free_rate: Annotated[Optional[float], Field(description='Risk-free rate as a decimal (e.g. 0.04 for 4%).')] = None,
    beta: Annotated[Optional[float], Field(description='Systematic risk beta (market = 1.0).')] = None,
    mrp: Annotated[Optional[float], Field(description='Market risk premium as a decimal.')] = None,
    crp: Annotated[Optional[float], Field(description='Country risk premium as a decimal.')] = None,
) -> dict[str, Any]:
    """Cross-border adjustments: purchasing-power parity, country risk premium, and international CAPM."""
    return call_tool('valuation_international', {'method': method, 'spot_rate': spot_rate, 'inflation_foreign': inflation_foreign, 'inflation_domestic': inflation_domestic, 'sovereign_yield': sovereign_yield, 'us_treasury_yield': us_treasury_yield, 'risk_free_rate': risk_free_rate, 'beta': beta, 'mrp': mrp, 'crp': crp})


@mcp.tool(
    name='valuation_stakeholder',
    title='Stakeholder & Equity Allocation',
    description='Allocate value across stakeholders and equity classes: single-round dilution, OPM common stock, PWERM, liquidation value, M&A synergy, employee-option values, vesting adjustment, cash-vs-equity break-even, and asset-based loan capacity. Method selects the model. Use only after the company-level value is known (from valuation_core, valuation_saas, or valuation_comparables) to split that value across the cap table; for the company value itself do not use this tool. Parameters apply per method: dilution needs ownership_before + investment + post_money; opm needs enterprise_value + liquidation_pref + time_to_exit + volatility; pwerm and employee_option need scenarios; liquidation needs assets + recovery_rates; risk_adjusted_synergy needs revenue_synergies + cost_synergies; vesting_adjusted needs total_value + vested_fraction; max_asset_loan takes collateral values. Only method is required; all other parameters are method-dependent, so supply those the selected method names and omit the rest (defaults apply where defined). Rate and decimal inputs are fractions (0.10 = 10%); probability and weight lists are in [0,1] and sum to 1. Returns value, method, inputs, assumptions, chapter, formula_number and calculation steps; pure arithmetic — no I/O and no external calls — rounded to 2 decimals, with no auth or rate limits. An unknown method, or a missing method-required parameter, returns an error instead of a value.',
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'dilution', 'opm', 'pwerm', 'options', 'cap-table'},
)
def valuation_stakeholder(
    method: Annotated[Literal['dilution', 'opm', 'pwerm', 'liquidation', 'risk_adjusted_synergy', 'intrinsic_option', 'employee_option', 'vesting_adjusted', 'cash_equity_breakeven', 'max_asset_loan'], Field(description='Formula to apply. Options: dilution = Ownership = before × (1 - investment / post-money).; opm = Option-pricing allocation of equity value to common shares.; pwerm = Probability-weighted expected return method across exit scenarios.; liquidation = V = Σ(asset × recovery rate).; risk_adjusted_synergy = Probability-weighted, discounted M&A revenue + cost synergies.; intrinsic_option = Intrinsic value = max(0, FMV - strike) × shares.; employee_option = Probability-weighted employee option value across scenarios.; vesting_adjusted = Option value adjusted for vesting schedule and retention probability.; cash_equity_breakeven = Break-even comparing salary reduction against discounted equity.; max_asset_loan = Borrowing capacity from asset collateral values.')],
    ownership_before: Annotated[Optional[float], Field(description='Founder ownership before the round as a decimal (0.60 = 60%).')] = None,
    investment: Annotated[Optional[float], Field(description='Amount invested, currency units.')] = None,
    post_money: Annotated[Optional[float], Field(description='Post-money valuation, currency units.')] = None,
    enterprise_value: Annotated[Optional[float], Field(description='Enterprise value (market cap + net debt), currency units.')] = None,
    liquidation_pref: Annotated[Optional[float], Field(description='Liquidation preference amount, currency units.')] = None,
    time_to_exit: Annotated[Optional[float], Field(description='Expected time to exit / liquidity in years.')] = None,
    volatility: Annotated[Optional[float], Field(description='Annualised volatility σ as a decimal (0.80 = 80%).')] = None,
    scenarios: Annotated[Optional[list[dict[str, Any]]], Field(description='Scenario objects: {name: str, probability: 0-1, value: currency}; probabilities should sum to 1.')] = None,
    assets: Annotated[Optional[dict[str, Any]], Field(description='Map of asset name to book value, e.g. {"cash": 500000}.')] = None,
    recovery_rates: Annotated[Optional[dict[str, Any]], Field(description='Map of asset name to recovery rate in [0,1], matching assets.')] = None,
    revenue_synergies: Annotated[Optional[float], Field(description='Revenue synergy value, currency units.')] = None,
    cost_synergies: Annotated[Optional[float], Field(description='Cost synergy value, currency units.')] = None,
    prob_revenue: Annotated[Optional[float], Field(description='Probability of realising revenue synergies, 0-1.')] = None,
    prob_cost: Annotated[Optional[float], Field(description='Probability of realising cost synergies, 0-1.')] = None,
    discount_rate: Annotated[Optional[float], Field(description='Discount rate as a decimal (0.12 = 12%).')] = None,
    years: Annotated[Optional[int], Field(description='Forecast horizon in years; integer ≥ 1.')] = None,
    strike_price: Annotated[Optional[float], Field(description='Option strike price, currency units.')] = None,
    fair_market_value: Annotated[Optional[float], Field(description='Current fair market value per share, currency units.')] = None,
    shares: Annotated[Optional[int], Field(description='Number of option shares.')] = None,
    total_value: Annotated[Optional[float], Field(description='Total grant value, currency units.')] = None,
    vested_fraction: Annotated[Optional[float], Field(description='Fraction vested in [0,1].')] = None,
    annual_vest_rate: Annotated[Optional[float], Field(description='Annual vesting rate as a decimal.')] = None,
    retention_prob: Annotated[Optional[float], Field(description='Probability the holder stays, 0-1.')] = None,
    years_remaining: Annotated[Optional[int], Field(description='Years of vesting remaining.')] = None,
    salary_reduction: Annotated[Optional[float], Field(description='Annual salary foregone for equity, currency units.')] = None,
    equity_value: Annotated[Optional[float], Field(description='Value of equity offered, currency units.')] = None,
    tax_rate: Annotated[Optional[float], Field(description='Effective tax rate as a decimal in [0,1].')] = None,
    cash: Annotated[Optional[float], Field(description='Cash and equivalents, currency units.')] = None,
    accounts_receivable: Annotated[Optional[float], Field(description='Accounts receivable, currency units.')] = None,
    inventory: Annotated[Optional[float], Field(description='Inventory, currency units.')] = None,
    equipment: Annotated[Optional[float], Field(description='Equipment, currency units.')] = None,
    real_estate: Annotated[Optional[float], Field(description='Real estate, currency units.')] = None,
) -> dict[str, Any]:
    """Allocate value across stakeholders and equity classes: single-round dilution, OPM common stock, PWERM, liquidation value, M&A synergy, employee-option values, vesting adjustment, cash-vs-equity break-even, and asset-based loan capacity."""
    return call_tool('valuation_stakeholder', {'method': method, 'ownership_before': ownership_before, 'investment': investment, 'post_money': post_money, 'enterprise_value': enterprise_value, 'liquidation_pref': liquidation_pref, 'time_to_exit': time_to_exit, 'volatility': volatility, 'scenarios': scenarios, 'assets': assets, 'recovery_rates': recovery_rates, 'revenue_synergies': revenue_synergies, 'cost_synergies': cost_synergies, 'prob_revenue': prob_revenue, 'prob_cost': prob_cost, 'discount_rate': discount_rate, 'years': years, 'strike_price': strike_price, 'fair_market_value': fair_market_value, 'shares': shares, 'total_value': total_value, 'vested_fraction': vested_fraction, 'annual_vest_rate': annual_vest_rate, 'retention_prob': retention_prob, 'years_remaining': years_remaining, 'salary_reduction': salary_reduction, 'equity_value': equity_value, 'tax_rate': tax_rate, 'cash': cash, 'accounts_receivable': accounts_receivable, 'inventory': inventory, 'equipment': equipment, 'real_estate': real_estate})


@mcp.tool(
    name='valuation_emerging',
    title='Emerging & Alternative Methods',
    description='Modern and alternative valuation: SAFE conversion (discount, cap, expected value), token valuation (equation of exchange, NVT), ESG adjustments (rate, premium, discount), Metcalfe network value, data-moat value, and remote-first premium/NPV. Method selects the model. Use for SAFEs, tokens, ESG, network effects, data moats, and remote-first adjustments; for classic pre-revenue methods use valuation_core. Parameters apply per method: safe_discount needs series_a_price + discount; safe_cap needs cap + series_a_price; safe_expected needs investment + cap + discount + series_a_valuation + series_a_price; token_value needs transaction_volume + price_per_tx + velocity + supply; metcalfe needs n; esg_* need base_valuation + a score; data_moat needs data_volume + data_uniqueness + monetization_rate + competitive_advantage_years. Routing: for classic pre-revenue methods (Scorecard, Berkus, Risk-Factor Summation, VC Method) use valuation_core; for options or scenario tables use valuation_advanced; for public-comparable multiples use valuation_comparables. Only method is required; all other parameters are method-dependent, so supply those the selected method names and omit the rest (defaults apply where defined). Rate and decimal inputs are fractions (0.10 = 10%); probability and weight lists are in [0,1] and sum to 1. Returns value, method, inputs, assumptions, chapter, formula_number and calculation steps; pure arithmetic — no I/O and no external calls — rounded to 2 decimals, with no auth or rate limits. An unknown method, or a missing method-required parameter, returns an error instead of a value.',
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'safe', 'crypto', 'esg', 'network-effects', 'data'},
)
def valuation_emerging(
    method: Annotated[Literal['safe_discount', 'safe_cap', 'safe_expected', 'token_value', 'nvt_ratio', 'esg_rate', 'esg_premium', 'esg_discount', 'metcalfe', 'data_moat', 'remote_npv', 'remote_premium'], Field(description='Formula to apply. Options: safe_discount = Price = Series A price × (1 - discount).; safe_cap = Price = cap / pre-money shares (cap-based).; safe_expected = Expected SAFE value across cap and discount outcomes.; token_value = Value = (volume × price) / (velocity × supply).; nvt_ratio = NVT = market cap / daily transaction volume.; esg_rate = r = base + ESG risk premium - ESG opportunity discount.; esg_premium = Valuation uplift = base × (1 + score × premium per point).; esg_discount = Valuation reduction = base × (1 - risk score × discount per point).; metcalfe = V = k · n².; data_moat = Discounted value of monetised proprietary data.; remote_npv = Perpetuity NPV = annual savings / discount rate.; remote_premium = Valuation premium from cost savings, talent access, and productivity.')],
    series_a_price: Annotated[Optional[float], Field(description='Price per share in the next priced (Series A) round.')] = None,
    discount: Annotated[Optional[float], Field(description='Conversion discount as a decimal (0.20 = 20% discount).')] = None,
    cap: Annotated[Optional[float], Field(description='SAFE valuation cap, currency units.')] = None,
    investment: Annotated[Optional[float], Field(description='Amount invested, currency units.')] = None,
    series_a_valuation: Annotated[Optional[float], Field(description='Series A post-money valuation, currency units.')] = None,
    transaction_volume: Annotated[Optional[float], Field(description='Total payment transaction volume, currency units.')] = None,
    price_per_tx: Annotated[Optional[float], Field(description='Protocol revenue per transaction, currency units.')] = None,
    velocity: Annotated[Optional[float], Field(description='Token velocity (turnover of supply per period).')] = None,
    supply: Annotated[Optional[float], Field(description='Circulating token supply.')] = None,
    market_cap: Annotated[Optional[float], Field(description='Market capitalisation, currency units.')] = None,
    rate: Annotated[Optional[float], Field(description='Per-period discount rate as a decimal (0.10 = 10%).')] = None,
    esg_risk_premium: Annotated[Optional[float], Field(description='ESG risk premium added to the rate, as a decimal.')] = None,
    esg_opportunity_discount: Annotated[Optional[float], Field(description='ESG opportunity discount subtracted from the rate.')] = None,
    base_valuation: Annotated[Optional[float], Field(description='Pre-adjustment baseline valuation, currency units.')] = None,
    esg_score: Annotated[Optional[float], Field(description='ESG score in points (e.g. 0-100).')] = None,
    premium_per_point: Annotated[Optional[float], Field(description='Valuation premium per ESG point as a decimal.')] = None,
    esg_risk_score: Annotated[Optional[float], Field(description='ESG risk score in points (higher = riskier).')] = None,
    discount_per_point: Annotated[Optional[float], Field(description='Valuation discount per ESG risk point as a decimal.')] = None,
    n: Annotated[Optional[float], Field(description='Number of users or nodes in the network.')] = None,
    k: Annotated[Optional[int], Field(description='Number of events k for the Poisson probability P(X=k); integer ≥ 0.')] = None,
    data_volume: Annotated[Optional[float], Field(description='Volume of proprietary data held.')] = None,
    data_uniqueness: Annotated[Optional[float], Field(description='Uniqueness / scarcity of the data in [0,1].')] = None,
    monetization_rate: Annotated[Optional[float], Field(description='Fraction of data value monetisable as a decimal.')] = None,
    competitive_advantage_years: Annotated[Optional[float], Field(description='Years the data moat is expected to last.')] = None,
    discount_rate: Annotated[Optional[float], Field(description='Discount rate as a decimal (0.12 = 12%).')] = None,
    annual_savings: Annotated[Optional[float], Field(description='Annual cost savings, currency units.')] = None,
    cost_savings_pct: Annotated[Optional[float], Field(description='Cost savings as a fraction of baseline.')] = None,
    talent_access_premium: Annotated[Optional[float], Field(description='Talent-access premium as a decimal.')] = None,
    productivity_gain: Annotated[Optional[float], Field(description='Productivity gain as a decimal.')] = None,
) -> dict[str, Any]:
    """Modern and alternative valuation: SAFE conversion (discount, cap, expected value), token valuation (equation of exchange, NVT), ESG adjustments (rate, premium, discount), Metcalfe network value, data-moat value, and remote-first premium/NPV."""
    return call_tool('valuation_emerging', {'method': method, 'series_a_price': series_a_price, 'discount': discount, 'cap': cap, 'investment': investment, 'series_a_valuation': series_a_valuation, 'transaction_volume': transaction_volume, 'price_per_tx': price_per_tx, 'velocity': velocity, 'supply': supply, 'market_cap': market_cap, 'rate': rate, 'esg_risk_premium': esg_risk_premium, 'esg_opportunity_discount': esg_opportunity_discount, 'base_valuation': base_valuation, 'esg_score': esg_score, 'premium_per_point': premium_per_point, 'esg_risk_score': esg_risk_score, 'discount_per_point': discount_per_point, 'n': n, 'k': k, 'data_volume': data_volume, 'data_uniqueness': data_uniqueness, 'monetization_rate': monetization_rate, 'competitive_advantage_years': competitive_advantage_years, 'discount_rate': discount_rate, 'annual_savings': annual_savings, 'cost_savings_pct': cost_savings_pct, 'talent_access_premium': talent_access_premium, 'productivity_gain': productivity_gain})



def main() -> None:
    """Run the stdio MCP server (entry point)."""
    mcp.run()


if __name__ == "__main__":
    main()

